FROM nginx:1.14

COPY ./config-dev/configs /etc/nginx/
COPY ./config-dev/templates /etc/nginx/sites-enabled/

RUN mkdir /var/cache/nginx/client_temp && \
    mkdir /var/cache/nginx/proxy_temp && \
    mkdir /var/cache/nginx/fastcgi_temp && \
    mkdir /var/cache/nginx/scgi_temp

CMD ["nginx", "-g", "daemon off;"]